### PR TITLE
WIP - using pydantic

### PR DESCRIPTION
**Pull request by commonism**
Things escalated quickly and ended up with pydantic.
pydantic is used by fastapi for the server side of things, well tested library.

Now Schema.get_type() returns a pydantic ModelBase created using types.new_class.
allOf is resolved when creating the type, avoiding issues such as https://github.com/Dorthu/openapi3/pull/52

Some things, like parsing (root) context/path information is not available during parsing/validation in the nodes.
I tried to be as least disruptive as possible wrt. to the tests, but I would prefer to get rid of SpecError and stick to pydantic ValidationError instead.

Would be great if you could have a look.

### CODE REVIEW

**Comment by commonism** [comment]
I chose to fork -> aiopenapi3
https://github.com/commonism/aiopenapi3

**Comment by Dorthu** [comment]
Sorry for the delay, I was out for the holidays and wasn't keeping up with github.

This looks like a fairly large change, but if you don't feel like maintaining a fork I'd be happy to discuss what you're trying to do and consider it for merging here.

**Comment by commonism** [comment]
I'm looking for a openapi3 client library which is on par with the server side of things e.g. fastapi and can adapt to … non compliant implementations.

…
 * asyncio support - I choose httpx 
 * strict parsing of the description document - I choose pydantic
 * (pydantic) object creation/validation according to the description document, 
   * including (properly done) discrimination as supported by fastapi
 * suds inspired plugin interface to deal with real world api's (todo)

If you look at it, it's basically just some glue between pydantic and httpx, almost all the heavy lifting is done somewhere else.
Creating pydantic types from the description document is the non-so-easy part.

`Annotated` requires python 3.9, merging won't be easy without loosing compatibility in various dimensions, python versions & API changes.
I'd prefer to collaborate.

**Comment by Dorthu** [comment]
Having read through and played with this branch, the approach looks solid.  Using pydantic for spec parsing and validation certainly simplifies a lot of the implementation.

I would prefer to, at least by default, have this client _not_ adapt to non-complaint implementations - one of its goals is to allow validation of not just the parsed spec's format, but that the spec actually describes the API it claims to.  To that end, having this library produce errors if responses don't match what is described is important.  That said, I do understand why a permissive implementation would be desirable (for both the spec formatting and the client behavior), especially in situations where you don't control the spec itself.  If you think both of those could coexist (i.e. a configurable `strict` mode), that works for me.

I would prefer to keep this library compatible with at  least all presently supported python versions.  That said, it looks like `typing_extensions` implements `Annotated` for python versions before 3.9.

I am definitely open to collaborating on this and getting it merged in here if we're in alignment.

**Comment by commonism** [comment]
We agree. 
"can adapt to … non compliant implementations" = strict, with the ability to modify the description document, request, response *as required* to "make things work"

I'm not planning to accept invalid documents/responses, providing the ability to make them proper is fine.

I added a plugin interface to do this
https://github.com/commonism/aiopenapi3/blob/master/aiopenapi3/plugin.py
here is an example https://github.com/commonism/slurmrest/blob/development/slurmrest/improve.py#L62
```python
    api = OpenAPI.load_sync(config["url"], session_factory=session_factory,
                        plugins=[improve.OnDocument("v0.0.37"),
                                 improve.OnMessage()])
```
suds does the same for SOAP.

I just added the required bits to distinguish 3.1 from 3.0.
https://github.com/commonism/aiopenapi3/commit/97e5dfeb4f5e74faa7a043dde5170eadbf54e7b6
Required as 3.1 is basically 4.0, not backwards compatible.
It validates the 3.1 tests https://github.com/OAI/OpenAPI-Specification/tree/main/tests/v3.1 already.
The CI does not install the requirements and fails at the moment.

For python versions thats  3.7+, fine.
I guess it'll be walrus in some places, f'strings could be future-fstrings - overall it should be manageable.

**Comment by Dorthu** [comment]
I've caught up on PRs in this repo and released the latest as version 1.6.1.

How would you like to proceed with this?   Would you prefer to keep these changes in a fork while they're in development, then merge back in here when they're done?

**Comment by commonism** [comment]
I guess it'll be best to wait for it to settle for 1-2 weeks before merging.

I'd propose you merge/take over and I'll keep or re-create a repo to work on changes.

How do you want to proceed wrt. to openapi3 compatibility?
Increase version to 2.0, change the module name back to openapi3?.

**Comment by Dorthu** [comment]
This project is semantically versioned, so I figure bumping to 2.0 is good enough to cover the breaking changes.

I'll spend some time with your fork in the coming weeks and put everything through it's paces.  Should I open issues/PRs there for things I find?

**Comment by commonism** [comment]
I merged next, you can go ahead with master.
It does Swagger/v2.0 & OpenAPI 3.0/3.1 with python 3.{7,8,9,10}.
Tested using the openapi-directory … the description documents are archived - not validated, some fail due to missing dependencies and unicode violations, most require some special treatment to parseable.
It's about 3700 files, running for > 20 minutes.

```python

class TestParseData:
    # a map specifying multiple argument sets for a test method
    params = {
        "test_data": [("dir", "file"), "/tmp/openapi-directory/APIs", lambda x: x.is_file() and x.suffix in (".json", ".yaml")],
    }
    def test_data(self, dir, file):
        from aiopenapi3.plugin import Document
        class RemoveSourceFromRoot(Document):
            def parsed(self, ctx):
                if "source" in ctx.document:
                    del ctx.document["source"]
                return ctx

        OpenAPI.load_file(str(URLBASE / file), pathlib.Path(file), loader=FileSystemLoader(pathlib.Path(dir), yload=aiopenapi3.loader.YAMLCompatibilityLoader), plugins=[RemoveSourceFromRoot()])
```


linode.yaml will run into YAML type coercion https://github.com/commonism/aiopenapi3#yaml for not enclosing datetimes in ".

**Comment by commonism** [comment]
I had to change authentication due to a misunderstanding in security requirements.
> Security Requirement Objects that contain multiple schemes require that all schemes MUST be satisfied for a request to be authorized. 
https://github.com/commonism/aiopenapi3/commit/4253e5378574a7809788eca572f09957e314e57e#diff-c54e66b8cd7dc714949b4c88414af7355b2c2c82c29ac7192c40fa4218d28fbaR78

Required changing the signature of OpenAPI.authenticate.
https://github.com/commonism/aiopenapi3/commit/4253e5378574a7809788eca572f09957e314e57e#diff-37c590471d1a5e3da137bf12574e6dfd5755f4f7315ce9c29ab4d1cc02f56c4cR274

**Comment by commonism** [comment]
I re-included caching the Model types.

Whats your experience with it so far?

**Comment by Dorthu** [comment]
I hate to say that I haven't had much time to look at it yet 😕  I'll spend some time with it this weekend and open issues and/or PRs on your fork.

**Pull request closed without merging**
