### PR TITLE
Support float values for minimum and maximum

### LINKED ISSUE #29: openapi3.errors.SpecError when minimum/maximum validation is float
The following file::

<details><summary><code>openapi.json</code></summary>

```json
{
    "openapi": "3.0.3",
    "info": {
        "title": "Foo",
        "version": "1.0.0"
    },
    "paths": {
        "/foo": {
            "post": {
                "responses": {
                    "200": {
                        "description": "Foo.",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "type": "object",
                                    "properties": {
                                        "value": {
                                            "type": "number",
                                            "format": "double",
                                            "minimum": 0.0,
                                            "maximum": 1.0
                                        }
                                    }
                                }
                            }
                        }
                    }
                }
            }
        }
    }
}
```

</details>

Fails to load with the following error:

<details><summary>Traceback</summary>

```
Traceback (most recent call last):
  File "<censored>.py", line 5, in <module>
    api = OpenAPI(json.load(fd))
  File "<censored>/openapi.py", line 44, in __init__
    super(OpenAPI, self).__init__([], raw_document, self)
  File "<censored>/object_base.py", line 56, in __init__
    self._parse_data()
  File "<censored>/openapi.py", line 134, in _parse_data
    self.paths        = self._get('paths', ['Path'], is_map=True)
  File "<censored>/object_base.py", line 193, in _get
    ret = Map(self.path + [field], ret, object_types, self._root)
  File "<censored>/object_base.py", line 516, in __init__
    dct[k] = t(path + [k], v, self._root)
  File "<censored>/object_base.py", line 56, in __init__
    self._parse_data()
  File "<censored>/paths.py", line 36, in _parse_data
    self.post        = self._get('post', 'Operation')
  File "<censored>/object_base.py", line 209, in _get
    ret = python_type(self.path + [field], ret, self._root)
  File "<censored>/object_base.py", line 56, in __init__
    self._parse_data()
  File "<censored>/paths.py", line 102, in _parse_data
    self.responses    = self._get('responses', ['Response', 'Reference'], is_map=True)
  File "<censored>/object_base.py", line 193, in _get
    ret = Map(self.path + [field], ret, object_types, self._root)
  File "<censored>/object_base.py", line 516, in __init__
    dct[k] = t(path + [k], v, self._root)
  File "<censored>/object_base.py", line 56, in __init__
    self._parse_data()
  File "<censored>/paths.py", line 385, in _parse_data
    self.content     = self._get('content', ['MediaType'], is_map=True)
  File "<censored>/object_base.py", line 193, in _get
    ret = Map(self.path + [field], ret, object_types, self._root)
  File "<censored>/object_base.py", line 516, in __init__
    dct[k] = t(path + [k], v, self._root)
  File "<censored>/object_base.py", line 56, in __init__
    self._parse_data()
  File "<censored>/paths.py", line 365, in _parse_data
    self.schema   = self._get('schema', ['Schema', 'Reference'])
  File "<censored>/object_base.py", line 209, in _get
    ret = python_type(self.path + [field], ret, self._root)
  File "<censored>/object_base.py", line 56, in __init__
    self._parse_data()
  File "<censored>/schemas.py", line 50, in _parse_data
    self.properties           = self._get('properties', ['Schema', 'Reference'], is_map=True)
  File "<censored>/object_base.py", line 193, in _get
    ret = Map(self.path + [field], ret, object_types, self._root)
  File "<censored>/object_base.py", line 516, in __init__
    dct[k] = t(path + [k], v, self._root)
  File "<censored>/object_base.py", line 56, in __init__
    self._parse_data()
  File "<censored>/schemas.py", line 36, in _parse_data
    self.maximum              = self._get('maximum', int)
  File "<censored>/object_base.py", line 222, in _get
    raise SpecError('Expected {}.{} to be one of [{}], got {}'.format(
openapi3.errors.SpecError: Expected paths./foo.post.responses.200.content.application/json.schema.properties.value.maximum to be one of [<class 'int'>], got <class 'float'>
```

</details>

The specification reads ([section 5.2, validation schema](https://tools.ietf.org/html/draft-wright-json-schema-validation-00#section-5.2)):

> The value of "maximum" MUST be a number, representing an upper limit
> for a numeric instance.
> 
> If the instance is a number, then this keyword validates if
> "exclusiveMaximum" is true and instance is less than the provided
> value, or else if the instance is less than or exactly equal to the
> provided value.

The same happens with `minimum` (and probably the `exclusive*` variants, didn't bother to check).

A number is ([section 4.2, core schema](https://tools.ietf.org/html/draft-wright-json-schema-00#section-4.2)):

> number  An arbitrary-precision, base-10 decimal number value, from
> the JSON "number" production

Thus, the code should not be checking for `int` but `float`.

### PR DESCRIPTION
**Pull request by i-sf**
Closes #29.

Not sure why I bothered with such a detailed report when it would've taken me a lot less time to just send this patch.

### CODE REVIEW

**Comment by guyarb** [comment]
@i-sf this fix seems to have a bug as well, if you set `minimum` or `maximum` fields to an integer (i.e. `1` which is a valid float), it will fail after your fix. I think the solution should be setting types as `[int, float]`.

**Comment by i-sf** [comment]
Note that `type` and `format` is ignored. I could put `type: integer` and `format: int32` and use a `float`, and vice versa for the `number` `double`. This validation, which would probably be good to make, would require more changes, and is out of scope for this changeset (which is just support at all).

Aside: I spent an embarrasingly long time figuring out how lists for `_get` worked because I had to run `pip install` (which I wasn't doing) before `pytest` or it wouldn't pick up my changes. Do you know how to run `pytest` so that it uses the directory as the library without having to install it, or if it's possible at all?

**Comment by i-sf** [comment]
> # JSON Schema
>
> ### [4.2.1. Instance Data Model](https://json-schema.org/draft/2020-12/json-schema-core.html#rfc.section.4.2.1)
>
> * number:
>   An arbitrary-precision, base-10 decimal number value, from the JSON "number" value

And also:

> ## [6.3. Mathematical Integers](https://json-schema.org/draft/2020-12/json-schema-core.html#rfc.section.6.3)
> 
> Some programming languages and parsers use different internal representations for floating point numbers than they do for integers.
> 
> For consistency, integer JSON numbers SHOULD NOT be encoded with a fractional part. 

Both these sections seem to imply that floating point numbers are supported. It also says:

> The terms "JSON", "JSON text", "JSON value", "member", "element", "object", "array", "number", "string", "boolean", "true", "false", and "null" in this document are to be interpreted as defined in [RFC 8259](https://tools.ietf.org/html/rfc8259#section-6).

And from that RFC:

> ## [6. Numbers](https://tools.ietf.org/html/rfc8259#section-6)
>
> The representation of numbers is similar to that used in most programming languages.  A number is represented in base 10 using decimal digits.  It contains an integer component […] which may be followed by a fraction part and/or an exponent part.

---

I would not consider the above vague by any means. Note that it is the JSON Schema Core the one who talks about numbers. The JSON Schema Validation, which refers to `minimum`, simply refers to the `number` previously defined, which can clearly be a float. Even if this was not the case, dropping a fractional part would be way too much. It would mean `minimum: 0.1, maximum: 0.3` would make both 0.

**Comment by i-sf** [comment]
@Dorthu could you please take a look? Thanks. (If possible, https://github.com/Dorthu/openapi3/pull/34, https://github.com/Dorthu/openapi3/pull/35 and https://github.com/Dorthu/openapi3/pull/38 as well…)

**Comment by Dorthu** [comment]
Sorry I missed this , looking at the now

**Review by Dorthu — APPROVED** [review]

**Comment by Dorthu** [comment]
Sorry again for the delay; all of the above are released in version 1.4.0

**Pull request merged**
