### PR TITLE
tests - add fastapi based service for testing

### PR DESCRIPTION
**Pull request by commonism**
- fixes 204/reponses with without content

### CODE REVIEW

**Comment by Dorthu** [comment]
This is fantastic, I really appreciate the addition of tests for the client functionality 🙇‍♂️ 

I pushed up two commits to this branch; one just adds `fastapi` as a requirements for tests, and the other changes how 204s were handled to still produce an error if an endpoint returns a 204 response when the spec did not include that as a possible response code and had no default response .  If these look good to you, I'll merge this and cut a new release.

**Comment by commonism** [comment]
`expected_response.content is None` is allowed for more than 204, it's defined to be the only option for 204, but valid even for 200, if defined by the server.
Being liberal won't hurt though, maybe 
```
        elif expected_response.content is None:
            return
```
will work best?

**Comment by Dorthu** [comment]
Makes sense to me - I pushed that up 👍

**Comment by Dorthu** [comment]
I merged #57 - if this looks good now I'll merge it and cut a release.

**Comment by commonism** [comment]
Looking good.
Thanks.

**Pull request merged**
