### PR TITLE
un-escape ~1 and ~0 in paths, handle integers.

### LINKED ISSUE #74: Doesn't resolve JSON path escape codes
RFC 6901 says that `~1` must be de-escaped to `/` and `~0` is de-escaped to `~` (in this order).

### PR DESCRIPTION
**Pull request by smurfix**
Closes #74.

### CODE REVIEW

**Comment by smurfix** [comment]
Duh, forgot to remove the debug calls

**Review by Dorthu — APPROVED** [review]
This works great, thank you 👍

**Comment by Dorthu** [comment]
I'm going to try to secure reviews on #76 and #77, then merge them and publish a release

**Comment by smurfix** [comment]
> This works great, thank you +1

I sure hope so! Thanks for the prompt merge.

**Comment by Dorthu** [comment]
This, and the other changes from today, are published in version 1.6.4

**Pull request merged**
